version: '3.8'
services:
  backend:
    build: ./back_end
    ports:
      - "5000:5000"
    environment:
      ARANGO_URL: http://arango:8529
      ARANGO_DB: owl_db
      ARANGO_USER: root
      ARANGO_PASSWORD: example
      POSTGRES_DSN: postgresql://postgres:postgres@postgres:5432/forms
    depends_on:
      - arango
      - postgres
  frontend:
    build: ./front_end
    ports:
      - "3000:3000"
    depends_on:
      - backend
  arango:
    image: arangodb:3.11
    environment:
      ARANGO_ROOT_PASSWORD: example
    ports:
      - "8529:8529"
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forms
    ports:
      - "5432:5432"
